# Generated by Django 4.2.30 on 2026-06-10 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('image', 'Image')], max_length=10)),
                ('input_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('verdict', models.CharField(choices=[('REAL', 'Real'), ('FAKE', 'Fake'), ('UNCERTAIN', 'Uncertain')], default='UNCERTAIN', max_length=10)),
                ('credibility_score', models.IntegerField(default=50)),
                ('confidence_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('detected_category', models.CharField(blank=True, max_length=100)),
                ('key_claims', models.JSONField(default=list)),
                ('misleading_elements', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
